name: ci

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 25.1
          - 26.1
          - 27.1
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        check: melpa
        file: siri-shortcuts.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
